Disable auto-discovery for setuptools
With setuptools release 61.0.0 sahara-image-elements' package build
command (python3 setup.py sdist bdist_wheel) started to fail:

error: Multiple top-level packages discovered in a flat-layout:
['roles', 'elements', 'playbooks'].

This bug is mentioned in setuptools issue 3197 [1], and the suggested
workaround is to disable auto-discovery by adding 'py_modules=[]' in
setup.py.

To unblock the gate the following needed to be updated as well:
- requirements constraints
- fix lower-constraints job constraints (only the 1st constraints is
  used by pip, which was upper-constraints.txt from install command)

[1] https://github.com/pypa/setuptools/issues/3197

changes:
  tox.ini

NOTE(elod.illes): upper constraints should point to yoga version of the
file in stable/yoga.

Change-Id: Ib2d3e296e6d405671594dfd630e381ae414a2709
(cherry picked from commit 008b0d7e83bb75d89fed85db0a4a422519fd246b)